### ISSUE TITLE
Proposal: Generic telemetry packets

### ISSUE THREAD

**Issue by EternityForest** [ripplebiz/MeshCore#303]
It would be really nice to be able to easily publish sensor data and control home automation type devices, and maybe even build things like art installations that the public can control.

Other protocols usually seem to have very complicated and inflexible data formats for this, and the apps can only support the limited number of predefined sensors, which is a problem for the hobbyist community where people always have new ideas. They also lack any security at all.

I'm proposing, as a rough sketch, something like this:

* All sensor and control data is in the form of a msgpack object, with numbers as the keys, each number representing a data type.

* One of the data types is a request, which(if written to) would cause the device to send out a certain data ID, assuming it has that data.
 
* There is a predefined set of data IDs, for things like "solar input voltage", "small internal battery level", "generic event counter 1", "fault code list", "User social media profile", etc.   There's also a rage of undefined device-specific IDs.

All metadata would be stored in description files like:

```yaml
# This can be overridden by a device specific config
device_type:
    id: null
    fixed: Generic

device_type_version:
    fixed: null

device_type_uuid:
    fixed: 9f713797-f816-4492-aeca-dc62b7b86056

user_homepage:
   id: 67633
   type: string
   subtype: url
   # Device will never send this unless someone asks
   should_request: yes
 
solar_input_voltage:
    id: 24
    type: int
    # millivolts
    scale: 1000
    unit: volt
    min: 0
    max: 100
    writable: no
    icon: mdi-solar-power
```

If you want to send custom data types, you either make a PR and try to get the type you need in the master list, or you just publish a custom config file users can import into their apps. Unknown data objects just show as the raw values, which in many cases might be pretty obvious anyway.

Packets would be prefixed by a version byte, which could be compared against the custom config file version byte, to eliminate any mixups if versions get changed.

Packets would have a header, allowing for extra features.

Packets could also have an additional 4 byte auth code if enabled by header.  This would mean you can publish to a public channel while also giving the owner authentication,  control devices over open channels as required by HAM rules while still getting authentication, etc.

One predefined data type could be a millisecond timestamp, which could come in two flavors depending on whether the node is confident about the time(As in, it has a live GPS or NTP).   This would allow time sync, and also add replay prevention without adding extra data for packets that don't need it.

To mitigate mesh traffic issues, most data could be sent on request, or very rarely, default settings could be set up for once a day unless otherwise requested.
